### ISSUE TITLE
java.lang.NoClassDefFoundError: cpw/mods/modlauncher/Launcher

### ISSUE THREAD

**Issue by chakany** [ZekerZhayard/ForgeWrapper#4]
Got this error while trying to launch the installer for 1.12.2 2854. Anyone know what's up and how to fix?
![image](https://user-images.githubusercontent.com/30955604/103943546-471f1000-5100-11eb-995e-4303c2995250.png)

**Comment by ZekerZhayard** [comment]
ForgeWrapper is not designed for Minecraft Forge 1.12, it only can work on Forge 1.13+
